{% set version = '0.8.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dslabs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dslabs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dslabs/dslabs_{{ version }}.tar.gz
  sha256: f317a33addec6de8c8ecaa1740a891eb22dc5a3f9b8ecbc99c903725a544dda6

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('dslabs')"           # [not win]
    - "\"%R%\" -e \"library('dslabs')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=dslabs
  license: Artistic-2.0
  summary: Datasets and functions that can be used for data analysis practice, homework and projects
    in data science courses and workshops. 26 datasets are available for case studies
    in data visualization, statistical inference, modeling, linear regression, data
    wrangling and machine learning.
  license_family: OTHER
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'
extra:
  recipe-maintainers:
    - conda-forge/r
    - adamblake

# Package: dslabs
# Title: Data Science Labs
# Version: 0.8.0
# Description: Datasets and functions that can be used for data analysis practice, homework and projects in data science courses and workshops. 26 datasets are available for case studies in data visualization, statistical inference, modeling, linear regression, data wrangling and machine learning.
# Author: Rafael A. Irizarry, Amy Gill
# Maintainer: Rafael A. Irizarry <rafael_irizarry@dfci.harvard.edu>
# Depends: R (>= 3.5.0)
# Imports: ggplot2
# License: Artistic-2.0
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2024-03-01 15:20:18 UTC; rafa
# Repository: CRAN
# Date/Publication: 2024-03-01 16:42:37 UTC
